name: Release Packages

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
          version: 10.5.2

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm core:build

      - name: Get version
        id: get_version
        run: |
          CURRENT_VERSION=$(node -p 'require("./package.json").version')
          TAG="$CURRENT_VERSION"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            # 如果 tag 存在，增加 patch 版本号
            NEW_VERSION=$(node -p "require('semver').inc('$CURRENT_VERSION', 'patch')")
            echo "VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "NEW_VERSION=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Update version
        run: |
          if [ "${{ steps.get_version.outputs.VERSION }}" != "${{ steps.get_version.outputs.NEW_VERSION }}" ]; then
            # 更新所有包的版本号
            pnpm version ${{ steps.get_version.outputs.NEW_VERSION }} --no-git-tag-version
            cd apps/web && pnpm version ${{ steps.get_version.outputs.NEW_VERSION }} --no-git-tag-version
            cd ../../packages/core && pnpm version ${{ steps.get_version.outputs.NEW_VERSION }} --no-git-tag-version
            cd ../..
            # 提交版本更新
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "chore: bump version to ${{ steps.get_version.outputs.NEW_VERSION }}"
            git push
          fi

      - name: Create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          TAG="${{ steps.get_version.outputs.NEW_VERSION }}"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Publish to npm
        run: |
          cd packages/core
          npm pkg set name="emojito"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Package
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@emojito:registry=https://npm.pkg.github.com" >> .npmrc
          pnpm publish --filter=@emojito/core --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
